const fs = require('fs');

const targetFile = 'lib/mocks/world-data.ts';
let content = fs.readFileSync(targetFile, 'utf8');

const iso2Map = {
    'United States of America': 'US',
    'Russian Federation': 'RU',
    'China': 'CN',
    'Brazil': 'BR',
    'Australia': 'AU',
    'India': 'IN',
    'Argentina': 'AR',
    'Kazakhstan': 'KZ',
    'Algeria': 'DZ',
    'Democratic Republic of the Congo': 'CD',
    'Greenland': 'GL',
    'Saudi Arabia': 'SA',
    'Mexico': 'MX',
    'Indonesia': 'ID',
    'Sudan': 'SD',
    'Libya': 'LY',
    'Iran': 'IR',
    'Mongolia': 'MN',
    'Peru': 'PE',
    'Chad': 'TD',
    'Niger': 'NE',
    'Angola': 'AO',
    'Mali': 'ML',
    'South Africa': 'ZA',
    'Colombia': 'CO',
    'Ethiopia': 'ET',
    'Bolivia': 'BO',
    'Mauritania': 'MR',
    'Egypt': 'EG',
    'Tanzania': 'TZ',
    'Nigeria': 'NG',
    'Venezuela': 'VE',
    'Namibia': 'NA',
    'Mozambique': 'MZ',
    'Pakistan': 'PK',
    'Turkey': 'TR',
    'Chile': 'CL',
    'Zambia': 'ZM',
    'Myanmar': 'MM',
    'Afghanistan': 'AF',
    'South Sudan': 'SS',
    'France': 'FR',
    'Somalia': 'SO',
    'Central African Republic': 'CF',
    'Ukraine': 'UA',
    'Madagascar': 'MG',
    'Botswana': 'BW',
    'Kenya': 'KE',
    'Yemen': 'YE',
    'Thailand': 'TH',
    'Spain': 'ES',
    'Turkmenistan': 'TM',
    'Cameroon': 'CM',
    'Papua New Guinea': 'PG',
    'Sweden': 'SE',
    'Uzbekistan': 'UZ',
    'Morocco': 'MA',
    'Iraq': 'IQ',
    'Paraguay': 'PY',
    'Zimbabwe': 'ZW',
    'Norway': 'NO',
    'Japan': 'JP',
    'Germany': 'DE',
    'Republic of the Congo': 'CG',
    'Finland': 'FI',
    'Vietnam': 'VN',
    'Malaysia': 'MY',
    'Oman': 'OM',
    'Italy': 'IT',
    'Philippines': 'PH',
    'Ecuador': 'EC',
    'Burkina Faso': 'BF',
    'New Zealand': 'NZ',
    'Gabon': 'GA',
    'Guinea': 'GN',
    'United Kingdom': 'GB',
    'Uganda': 'UG',
    'Ghana': 'GH',
    'Romania': 'RO',
    'Laos': 'LA',
    'Guyana': 'GY',
    'Belarus': 'BY',
    'Senegal': 'SN',
    'Kyrgyzstan': 'KG',
    'Syria': 'SY',
    'Cambodia': 'KH',
    'Uruguay': 'UY',
    'Suriname': 'SR',
    'Tunisia': 'TN',
    'Bangladesh': 'BD',
    'Nepal': 'NP',
    'Tajikistan': 'TJ',
    'Greece': 'GR',
    'Nicaragua': 'NI',
    'North Korea': 'KP',
    'Malawi': 'MW',
    'Eritrea': 'ER',
    'Benin': 'BJ',
    'Honduras': 'HN',
    'Liberia': 'LR',
    'Bulgaria': 'BG',
    'Cuba': 'CU',
    'Guatemala': 'GT',
    'Iceland': 'IS',
    'South Korea': 'KR',
    'Hungary': 'HU',
    'Portugal': 'PT',
    'Jordan': 'JO',
    'Serbia': 'RS',
    'Azerbaijan': 'AZ',
    'Austria': 'AT',
    'United Arab Emirates': 'AE',
    'Czechia': 'CZ',
    'Panama': 'PA',
    'Sierra Leone': 'SL',
    'Ireland': 'IE',
    'Georgia': 'GE',
    'Sri Lanka': 'LK',
    'Lithuania': 'LT',
    'Latvia': 'LV',
    'Svalbard and Jan Mayen': 'SJ',
    'Togo': 'TG',
    'Croatia': 'HR',
    'Bosnia and Herzegovina': 'BA',
    'Costa Rica': 'CR',
    'Slovakia': 'SK',
    'Dominican Republic': 'DO',
    'Estonia': 'EE',
    'Denmark': 'DK',
    'Netherlands': 'NL',
    'Switzerland': 'CH',
    'Bhutan': 'BT',
    'Taiwan': 'TW',
    'Guinea-Bissau': 'GW',
    'Moldova': 'MD',
    'Belgium': 'BE',
    'Lesotho': 'LS',
    'Armenia': 'AM',
    'Solomon Islands': 'SB',
    'Albania': 'AL',
    'Equatorial Guinea': 'GQ',
    'Burundi': 'BI',
    'Haiti': 'HT',
    'Rwanda': 'RW',
    'Macedonia': 'MK',
    'Djibouti': 'DJ',
    'Belize': 'BZ',
    'El Salvador': 'SV',
    'Israel': 'IL',
    'Slovenia': 'SI',
    'New Caledonia': 'NC',
    'Fiji': 'FJ',
    'Kuwait': 'KW',
    'Swaziland': 'SZ',
    'Timor-Leste': 'TL',
    'The Bahamas': 'BS',
    'Montenegro': 'ME',
    'Vanuatu': 'VU',
    'Falkland Islands': 'FK',
    'Qatar': 'QA',
    'Gambia': 'GM',
    'Jamaica': 'JM',
    'Lebanon': 'LB',
    'Cyprus': 'CY',
    'Puerto Rico': 'PR',
    'French Southern and Antarctic Lands': 'TF',
    'Palestine': 'PS',
    'Brunei': 'BN',
    'Trinidad and Tobago': 'TT',
    'Cape Verde': 'CV',
    'French Polynesia': 'PF',
    'Samoa': 'WS',
    'Luxembourg': 'LU',
    'Mauritius': 'MU',
    'Comoros': 'KM',
    'Sao Tome and Principe': 'ST',
    'Hong Kong': 'HK',
    'Dominica': 'DM',
    'Tonga': 'TO',
    'Micronesia': 'FM',
    'Singapore': 'SG',
    'Bahrain': 'BH',
    'Saint Lucia': 'LC',
    'Isle of Man': 'IM',
    'Guam': 'GU',
    'Andorra': 'AD',
    'Northern Mariana Islands': 'MP',
    'Palau': 'PW',
    'Seychelles': 'SC',
    'Curaçao': 'CW',
    'Antigua and Barbuda': 'AG',
    'Barbados': 'BB',
    'Turks and Caicos Islands': 'TC',
    'Saint Vincent and the Grenadines': 'VC',
    'U.S. Virgin Islands': 'VI',
    'Grenada': 'GD',
    'Malta': 'MT',
    'Maldives': 'MV',
    'Cayman Islands': 'KY',
    'Saint Kitts and Nevis': 'KN',
    'Niue': 'NU',
    'Saint Pierre and Miquelon': 'PM',
    'Cook Islands': 'CK',
    'American Samoa': 'AS',
    'Marshall Islands': 'MH',
    'Aruba': 'AW',
    'Liechtenstein': 'LI',
    'British Virgin Islands': 'VG',
    'Wallis and Futuna': 'WF',
    'Jersey': 'JE',
    'Montserrat': 'MS',
    'Anguilla': 'AI',
    'Guernsey': 'GG',
    'San Marino': 'SM',
    'Bermuda': 'BM',
    'St. Martin (French part)': 'MF',
    'Pitcairn Islands': 'PN',
    'Tuvalu': 'TV',
    'Nauru': 'NR',
    'Sint Maarten': 'SX',
    'Macao': 'MO',
    'Monaco': 'MC',
    'Vatican': 'VA',
    'W. Sahara': 'EH'
};

const getFlagEmoji = (countryCode) => {
    if (!countryCode) return '';
    const codePoints = countryCode
        .toUpperCase()
        .split('')
        .map(char => 127397 + char.charCodeAt());
    return String.fromCodePoint(...codePoints);
};

let lines = content.split('\n');
let replacedHtml = 0;

for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('bandeira: ""')) {
        let nameMatch = lines[i].match(/nome: "([^"]+)"/);
        if (nameMatch) {
            let nName = nameMatch[1];
            let iso2 = iso2Map[nName];
            if (iso2) {
                lines[i] = lines[i].replace('bandeira: ""', `bandeira: "${getFlagEmoji(iso2)}"`);
            } else {
                lines[i] = lines[i].replace('bandeira: ""', `bandeira: "🗺️"`);
            }
            replacedHtml++;
        }
    }
}

content = lines.join('\n');

fs.writeFileSync(targetFile, content);
console.log('Replaced ' + replacedHtml + ' empty flag emojis using iso2 table.');
